services:
  gen-03s:
    build: ./generator
    image: log-generator:latest
    container_name: log-generator-03s
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      INSTANCE_ID: "g03"
      SERVICE_NAME: "demo-app-03s"
      LOG_INTERVAL: "3"
      LOGSTASH_HOST: "host.docker.internal"
      LOGSTASH_PORT: "8091"
      TCP_OUTPUT: "true"
      RETRY_EVERY: "15"
      ERROR_RATE: "0.60"
      SPRING_RATE: "0.45"
      NON_JSON_RATE: "0.25"

  gen-08s:
    build: ./generator
    image: log-generator:latest
    container_name: log-generator-08s
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      INSTANCE_ID: "g08"
      SERVICE_NAME: "demo-app-08s"
      LOG_INTERVAL: "8"
      LOGSTASH_HOST: "host.docker.internal"
      LOGSTASH_PORT: "8091"
      TCP_OUTPUT: "true"
      RETRY_EVERY: "15"
      ERROR_RATE: "0.60"
      SPRING_RATE: "0.45"
      NON_JSON_RATE: "0.25"

  gen-15s:
    build: ./generator
    image: log-generator:latest
    container_name: log-generator-15s
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      INSTANCE_ID: "g15"
      SERVICE_NAME: "demo-app-15s"
      LOG_INTERVAL: "15"
      LOGSTASH_HOST: "host.docker.internal"
      LOGSTASH_PORT: "8091"
      TCP_OUTPUT: "true"
      RETRY_EVERY: "15"
      ERROR_RATE: "0.60"
      SPRING_RATE: "0.45"
      NON_JSON_RATE: "0.25"

  gen-22s:
    build: ./generator
    image: log-generator:latest
    container_name: log-generator-22s
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      INSTANCE_ID: "g22"
      SERVICE_NAME: "demo-app-22s"
      LOG_INTERVAL: "22"
      LOGSTASH_HOST: "host.docker.internal"
      LOGSTASH_PORT: "8091"
      TCP_OUTPUT: "true"
      RETRY_EVERY: "15"
      ERROR_RATE: "0.60"
      SPRING_RATE: "0.45"
      NON_JSON_RATE: "0.25"

  gen-30s:
    build: ./generator
    image: log-generator:latest
    container_name: log-generator-30s
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      INSTANCE_ID: "g30"
      SERVICE_NAME: "demo-app-30s"
      LOG_INTERVAL: "30"
      LOGSTASH_HOST: "host.docker.internal"
      LOGSTASH_PORT: "8091"
      TCP_OUTPUT: "true"
      RETRY_EVERY: "15"
      ERROR_RATE: "0.60"
      SPRING_RATE: "0.45"
      NON_JSON_RATE: "0.25"